[gitHubWebhook.config]
# The port that is used to start the webhook
WEBHOOK_PORT = 9090

# GitHub Webhook Service URL
GITHUB_URL = "https://api.github.com/hub"

# GitHub Webhook Topic
TOPIC_URL = "https://github.com/{owner}/{repo}/events/*.json"

# Public URL for the Subscriber Service
CALLBACK_URL = "https://"

# Secret Key to be used to authenticate content
SECRET = "test123#"

# Gsheet Config
AUTH_URL = "https://auth"

GSHEET_API = "https://sheets.google.com"
